Project/Models/Question.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    [Table("QUESTIONS", Schema = "ORACLE")]
    public class Question

    {
        [Key]
        [Column("QUESTIONID")]
        public int QuestionId { get; set; }

        [Column("QUESTIONTEXT")]
        public string? QuestionText { get; set; }

        [Column("OPTIONA")]
        public string? OptionA { get; set; }
        
        [Column("OPTIONB")]
        public string? OptionB { get; set; }
        [Column("OPTIONC")]
        public string? OptionC { get; set; }
        [Column("OPTIOND")]
        public string? OptionD { get; set; }
        [Column("CORRECTOPTION")]
        public string? CorrectOption { get; set; }
        [Column("CHAPTER")]
        public string? Chapter { get; set; }

        [Column("SUBJECTID")]
        public string? SubjectId { get; set; }
    }
}

Project/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;
using Project.Models;
using Project.Utilities;
using System.Collections;
using System.Data.Entity;
using System.Net.WebSockets;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
	
    public class MenuController : Controller
    {
		private readonly DataContext _dataContext;
		public String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
		
        
        public MenuController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public IActionResult Index()
        {
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
			
            return View(listofMenu);
			
        }
	
		public IActionResult Delete(int? id)
		{
			var query = "delete from menu where menuid =" + id;
			 String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
			var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
			connection.Open();
			var sourQuery = connection.CreateCommand();
			sourQuery.CommandText = query;
			sourQuery.ExecuteNonQuery();
			//var reader = sourQuery.ExecuteReader();
			connection.Close();
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return View("Index",listofMenu);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
            var sql = "SELECT * FROM menu ";
            var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return RedirectToAction("Index",mn);
		}

		public IActionResult Edit(int? id)
		{
			if (id == null)
				return NotFound();
			var sql = "SELECT * FROM menu where menu.MenuId ="+id;
			var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
			return View(mn);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Menu mn)
		{
			if(ModelState.IsValid)
			{
				var query = "update menu mn set mn.MenuName = '"+mn.MenuName+ "' where mn.MenuId = "+mn.MenuId;
				String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
				var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
				connection.Open();
				var sourQuery = connection.CreateCommand();
				sourQuery.CommandText = query;
				sourQuery.ExecuteNonQuery();
				//var reader = sourQuery.ExecuteReader();
				connection.Close();
			}
			return View(mn);
		}

		public IActionResult Create()
		{
            var parentList = (from
                             b in _dataContext.MENU
                               select new SelectListItem()
                               {
                                   Text = b.MenuName,
                                   Value = b.MenuId.ToString(),
                               }).ToList();
            parentList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.parentList = parentList;

            var menuOrderList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Vị trí 1", Value = "1" },
                new SelectListItem { Text = "Vị trí 2", Value = "2" },
                new SelectListItem { Text = "Vị trí 3", Value = "3" },
                new SelectListItem { Text = "Vị trí 4", Value = "4" },
                new SelectListItem { Text = "Vị trí 5", Value = "5" },
                new SelectListItem { Text = "Vị trí 6", Value = "6" },
                new SelectListItem { Text = "Vị trí 7", Value = "7" },
                new SelectListItem { Text = "Vị trí 8", Value = "8" },
            };
            ViewBag.MenuOrderList = menuOrderList;
            return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Menu mn)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_dataContext.MENU.Add(mn);
					_dataContext.SaveChanges();
					return RedirectToAction("Index");

				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View(mn);
		}

	}
}

Project/Areas/Admin/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Project.Models;
using Project.Utilities;
using System.Data.Entity;
using System.Reflection.Metadata;
using System.Text.RegularExpressions;
using static System.Net.Mime.MediaTypeNames;


namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class QuestionController : Controller
    {
        private readonly DataContext _dataContext;
        public QuestionController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public IActionResult Index()
        {
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var listOfQuestion = _dataContext.QUESTIONS.OrderByDescending(x => x.QuestionId).ToList();
            return View("Index", listOfQuestion);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var sb = _dataContext.QUESTIONS.Where(x => x.QuestionId == id).ToList();
            Question mn = sb.FirstOrDefault();
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var dl = _dataContext.QUESTIONS.Where(x => x.QuestionId == id).ToList();
            Question deleQUESTIONS = dl.FirstOrDefault();
            if (deleQUESTIONS == null)
            {
                return NotFound();
            }
            _dataContext.QUESTIONS.Remove(deleQUESTIONS);
            _dataContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var sb = _dataContext.QUESTIONS.Where(x => x.QuestionId == id).ToList();
            Question mn = sb.FirstOrDefault();
            if (mn == null)
            {
                return NotFound();
            }
            var answerList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Đáp án A", Value = "A" },
                new SelectListItem { Text = "Đáp án B", Value = "B" },
                new SelectListItem { Text = "Đáp án C", Value = "C" },
                new SelectListItem { Text = "Đáp án D", Value = "D" },
            };
            ViewBag.AnswerList = answerList;

            var chapterList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Chương I", Value = "1" },
                new SelectListItem { Text = "Đáp án II", Value = "2" },
                new SelectListItem { Text = "Đáp án III", Value = "3" },
                new SelectListItem { Text = "Đáp án IV", Value = "4" },
                new SelectListItem { Text = "Đáp án V", Value = "5" },
                new SelectListItem { Text = "Đáp án VI", Value = "6" },
                new SelectListItem { Text = "Đáp án VII", Value = "7" },
                new SelectListItem { Text = "Đáp án VIII", Value = "8" },
            };
            ViewBag.ChapterList = chapterList;

            return View(mn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Question mn)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _dataContext.QUESTIONS.Update(mn);
                    _dataContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(mn);
        }

        public IActionResult Create()
        {
            var answerList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Đáp án A", Value = "A" },
                new SelectListItem { Text = "Đáp án B", Value = "B" },
                new SelectListItem { Text = "Đáp án C", Value = "C" },
                new SelectListItem { Text = "Đáp án D", Value = "D" },
            };
            ViewBag.AnswerList = answerList;

            var chapterList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Chương I", Value = "1" },
                new SelectListItem { Text = "Chương II", Value = "2" },
                new SelectListItem { Text = "Chương III", Value = "3" },
                new SelectListItem { Text = "Chương IV", Value = "4" },
                new SelectListItem { Text = "Chương V", Value = "5" },
                new SelectListItem { Text = "Chương VI", Value = "6" },
                new SelectListItem { Text = "Chương VII", Value = "7" },
                new SelectListItem { Text = "Chương VIII", Value = "8" },
            };
            ViewBag.ChapterList = chapterList;

            var subjectList = (from
                             b in _dataContext.SUBJECT
                              select new SelectListItem()
                              {
                                  Text = b.SubjectName,
                                  Value = b.SubjectId.ToString(),
                              }).ToList();
            subjectList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.subjectList = subjectList;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Question mn)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _dataContext.QUESTIONS.Add(mn);
                    _dataContext.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(mn);
        }

        public IActionResult CreateMany()
        {
            var chapterList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Chương I", Value = "1" },
                new SelectListItem { Text = "Chương II", Value = "2" },
                new SelectListItem { Text = "Chương III", Value = "3" },
                new SelectListItem { Text = "Chương IV", Value = "4" },
                new SelectListItem { Text = "Chương V", Value = "5" },
                new SelectListItem { Text = "Chương VI", Value = "6" },
                new SelectListItem { Text = "Chương VII", Value = "7" },
                new SelectListItem { Text = "Chương VIII", Value = "8" },
            };
            chapterList.Insert(0, new SelectListItem()
                {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.chapterList = chapterList;
            // Tạo view bag các chapter

            var subjectList = (from
                             b in _dataContext.SUBJECT
                               select new SelectListItem()
                               {
                                   Text = b.SubjectName,
                                   Value = b.SubjectId.ToString(),
                               }).ToList();
            subjectList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.subjectList = subjectList;
            // tạo viewbag các subject
            return View();
        }
        [HttpPost]

        public IActionResult CreateMany(String inputFile, String ChapterId, String SubjectId)
        {
            try
            {
                String inputFile1 = @"D:\test.txt";
                
                //@"D:\test.txt";
                List<Question> listQuestion = new List<Question>();

                List<Question> questions = new List<Question>();

                if (System.IO.File.Exists(inputFile1))
                {
                    StreamReader reader = new StreamReader(inputFile1);
                    String? text = reader.ReadToEnd();
                    List<string> ques = new List<string>();
                    var matches = Regex.Matches(text, @"(Câu hỏi.*?)(?=Câu hỏi|$)", RegexOptions.Singleline);

                    foreach (Match match in matches)
                    {
                        var questext = Regex.Match(match.Value, @"Câu hỏi\s*:\s*(.*?)(?=\s*A\.)").Groups[1].Value.Trim();
                        var optA = Regex.Match(match.Value, @"A\.\s*(.*?)(?=\s*B\.)").Groups[1].Value.Trim();
                        var optB = Regex.Match(match.Value, @"B\.\s*(.*?)(?=\s*C\.)").Groups[1].Value.Trim();
                        var optC = Regex.Match(match.Value, @"C\.\s*(.*?)(?=\s*D\.)").Groups[1].Value.Trim();
                        var optD = Regex.Match(match.Value, @"D\.\s*(.*?)(?=\s*Đáp án)").Groups[1].Value.Trim();
                        var corOpt = Regex.Match(match.Value, @"Đáp án\s*:\s*(.*)").Groups[1].Value.Trim();

                        questions.Add(new Question
                        {
                            QuestionText = questext,
                            OptionA = optA,
                            OptionB = optB,
                            OptionC = optC,
                            OptionD = optD,
                            CorrectOption = corOpt,
                            Chapter = ChapterId,
                            SubjectId = SubjectId,
                        });
                    }

                    reader.Close();
                }
                else
                {                    
                    return StatusCode(404, "File không tồn tại");
                }           
                _dataContext.QUESTIONS.AddRange(questions);

Project/Areas/Admin/Views/Question/Create.cshtml
@model Project.Models.Question

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận thêm câu hỏi</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm</h2>
        </div>
        <form method="post">
            <div bsp-validation-summary="All"></div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="QuestionText">Câu hỏi</label>
                    <input type="text" class="form-control mb-3" asp-for="QuestionText" placeholder="Nhập câu hỏi">
                    <span asp-validation-for="QuestionText" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OptionA">Đáp án A</label>
                    <input type="text" class="form-control mb-3" asp-for="OptionA" placeholder="Nhập đáp án A">
                    <span asp-validation-for="OptionA" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OptionB">Đáp án B</label>
                    <input type="text" class="form-control mb-3" asp-for="OptionB" placeholder="Nhập đáp án B">
                    <span asp-validation-for="OptionB" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OptionC">Đáp án C</label>
                    <input type="text" class="form-control mb-3" asp-for="OptionC" placeholder="Nhập đáp án C">
                    <span asp-validation-for="OptionC" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="OptionA">Đáp án D</label>
                    <input type="text" class="form-control mb-3" asp-for="OptionD" placeholder="Nhập đáp án D">
                    <span asp-validation-for="OptionD" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="CorrectOption">Chọn đáp án đúng</label>
                <select asp-for="CorrectOption" class="form-control" asp-items="@(new SelectList(ViewBag.AnswerList,"Value","Text"))"></select>
                <span asp-validation-for="CorrectOption" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="CorrectOption">Chọn Chương</label>
                <select asp-for="CorrectOption" class="form-control" asp-items="@(new SelectList(ViewBag.ChapterList,"Value","Text"))"></select>
                <span asp-validation-for="CorrectOption" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="SubjectId">Chọn Môn học</label>
                <select asp-for="SubjectId" class="form-control" asp-items="@(new SelectList(ViewBag.subjectList,"Value","Text"))"></select>
                <span asp-validation-for="SubjectId" class="alert-danger"></span>
            </div>
            <div class="form-row">

                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Question" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Question/CreateMany.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận thêm gói câu hỏi</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm</h2>
        </div>
        <form method="post" asp-area="Admin" asp-controller="Question" asp-action="CreateMany">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputFile">Nhập URL file word</label>
                    <input type="text" class="form-control mb-3" name="inputFile" placeholder="Nhập đường dẫn">
                </div>
            </div>
 
            <div class="form-group col-md-6">
                <label for="ChapterId">Chọn chương</label>
                <select name="ChapterId" class="form-control" asp-items="@(new SelectList(ViewBag.chapterList,"Value","Text"))"></select>
                
            </div>
            <div class="form-group col-md-6">
                <label for="SubjectId">Chọn môn</label>
                <select name="SubjectId" class="form-control" asp-items="@(new SelectList(ViewBag.subjectList,"Value","Text"))"></select>

            </div>
           
            <div class="form-row">
                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Question" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Question/Edit.cshtml
@model Project.Models.Question
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận sửa câu hỏi</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Sửa câu hỏi</h2>
        </div>
        <form method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-row">
                <input type="text" class="form-control mb-3" asp-for="QuestionId" type="hidden">
                <div class="form-group col-md-6">
                    <label asp-for="QuestionText">Câu hỏi</label>
                    <input type="text" class="form-control mb-3" asp-for="QuestionText" placeholder="Nhập câu hỏi">
                    <span asp-validation-for="QuestionText" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-row">

                    <div class="form-group col-md-6">
                        <label asp-for="OptionA">Đáp án A</label>
                        <input type="text" class="form-control mb-3" asp-for="OptionA" placeholder="Đáp án A">
                        <span asp-validation-for="OptionA" class=" alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="OptionA">Đáp án B</label>
                        <input type="text" class="form-control mb-3" asp-for="OptionB" placeholder="Đáp án B">
                        <span asp-validation-for="OptionB" class=" alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="OptionC">Đáp án C</label>
                        <input type="text" class="form-control mb-3" asp-for="OptionC" placeholder="Đáp án C">
                        <span asp-validation-for="OptionC" class=" alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="OptionD">Đáp án D</label>
                        <input type="text" class="form-control mb-3" asp-for="OptionA" placeholder="Đáp án D">
                        <span asp-validation-for="OptionD" class=" alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="CorrectOption">Chọn đáp án đúng</label>
                        <select asp-for="CorrectOption" class="form-control" asp-items="@(new SelectList(ViewBag.AnswerList,"Value","Text"))"></select>
                        <span asp-validation-for="CorrectOption" class="alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="CorrectOption">Chọn chương</label>
                        <select asp-for="CorrectOption" class="form-control" asp-items="@(new SelectList(ViewBag.ChapterList,"Value","Text"))"></select>
                        <span asp-validation-for="CorrectOption" class="alert-danger"></span>
                    </div>



                </div>
                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Menu" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Question/Index.cshtml
@using Project.Models;
@model IList<Question>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách câu hỏi</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Question" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1">Thêm câu hỏi</i>
        </a>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Question" asp-action="CreateMany">
            <i class="bi bi-file-earmark-text me-1">Thêm gói câu hỏi</i>
        </a>
    </p>

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Câu hỏi</th>
                                    <th class="col-2 text-center">Đáp án A</th>
                                    <th class="col-2 text-center">Đáp án B</th>
                                    <th class="col-2 text-center">Đáp án C</th>
                                    <th class="col-2 text-center">Đáp án D</th>
                                    <th class="col-2 text-center">Đáp án đúng</th>
                                    
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.QuestionId</th>
                                       
                                        <td class="text-center">@item.QuestionText</td>
                                        <td class="text-center">@item.OptionA</td>
                                        <td class="text-center">@item.OptionB</td>
                                        <td class="text-center">@item.OptionC</td>
                                        <td class="text-center">@item.OptionD</td>
                                        <td class="text-center">@item.CorrectOption</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="Question" asp-action="Edit" asp-route-id="@item.QuestionId" class="btn btn-primary btn-sm" title="Sửa câu hỏi"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="Question" asp-action="Delete" asp-route-id="@item.QuestionId" class="btn btn-danger btn-sm" title="Xóa câu hỏi"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Project/Areas/Admin/Views/Question/ResultAfterInsertMany.cshtml
@using Project.Models;
@model IList<Question>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách câu hỏi vừa thêm vào</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Question" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1">Thêm câu hỏi</i>
        </a>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Question" asp-action="CreateMany">
            <i class="bi bi-file-earmark-text me-1">Thêm gói câu hỏi</i>
        </a>
    </p>

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Câu hỏi</th>
                                    <th class="col-2 text-center">Đáp án A</th>
                                    <th class="col-2 text-center">Đáp án B</th>
                                    <th class="col-2 text-center">Đáp án C</th>
                                    <th class="col-2 text-center">Đáp án D</th>
                                    <th class="col-2 text-center">Đáp án đúng</th>

                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.QuestionId</th>

                                        <td class="text-center">@item.QuestionText</td>
                                        <td class="text-center">@item.OptionA</td>
                                        <td class="text-center">@item.OptionB</td>
                                        <td class="text-center">@item.OptionC</td>
                                        <td class="text-center">@item.OptionD</td>
                                        <td class="text-center">@item.CorrectOption</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="Question" asp-action="Edit" asp-route-id="@item.QuestionId" class="btn btn-primary btn-sm" title="Sửa câu hỏi"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="Question" asp-action="Delete" asp-route-id="@item.QuestionId" class="btn btn-danger btn-sm" title="Xóa câu hỏi"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>