Project/Models/Subject.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{

    [Table("SUBJECT", Schema = "ORACLE")]
    public class Subject

    {
        [Key]
        [Column("SUBJECTID")]
        public int SubjectId { get; set; }

        [Column("SUBJECTNAME")]
        public string? SubjectName { get; set; }

        [Column("DESCRIPTION")]
        public string? Description { get; set; }

        
    }
}

Project/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;
using Project.Models;
using Project.Utilities;
using System.Collections;
using System.Data.Entity;
using System.Net.WebSockets;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
	
    public class MenuController : Controller
    {
		private readonly DataContext _dataContext;
		public String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
		
        
        public MenuController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public IActionResult Index()
        {
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
			
            return View(listofMenu);
			
        }
	
		public IActionResult Delete(int? id)
		{
			var query = "delete from menu where menuid =" + id;
			 String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
			var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
			connection.Open();
			var sourQuery = connection.CreateCommand();
			sourQuery.CommandText = query;
			sourQuery.ExecuteNonQuery();
			//var reader = sourQuery.ExecuteReader();
			connection.Close();
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return View("Index",listofMenu);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
            var sql = "SELECT * FROM menu ";
            var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return RedirectToAction("Index",mn);
		}

		public IActionResult Edit(int? id)
		{
			if (id == null)
				return NotFound();
			var sql = "SELECT * FROM menu where menu.MenuId ="+id;
			var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
			return View(mn);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Menu mn)
		{
			if(ModelState.IsValid)
			{
				var query = "update menu mn set mn.MenuName = '"+mn.MenuName+ "' where mn.MenuId = "+mn.MenuId;
				String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
				var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
				connection.Open();
				var sourQuery = connection.CreateCommand();
				sourQuery.CommandText = query;
				sourQuery.ExecuteNonQuery();
				//var reader = sourQuery.ExecuteReader();
				connection.Close();
			}
			return View(mn);
		}

		public IActionResult Create()
		{
            var parentList = (from
                             b in _dataContext.MENU
                               select new SelectListItem()
                               {
                                   Text = b.MenuName,
                                   Value = b.MenuId.ToString(),
                               }).ToList();
            parentList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.parentList = parentList;

            var menuOrderList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Vị trí 1", Value = "1" },
                new SelectListItem { Text = "Vị trí 2", Value = "2" },
                new SelectListItem { Text = "Vị trí 3", Value = "3" },
                new SelectListItem { Text = "Vị trí 4", Value = "4" },
                new SelectListItem { Text = "Vị trí 5", Value = "5" },
                new SelectListItem { Text = "Vị trí 6", Value = "6" },
                new SelectListItem { Text = "Vị trí 7", Value = "7" },
                new SelectListItem { Text = "Vị trí 8", Value = "8" },
            };
            ViewBag.MenuOrderList = menuOrderList;
            return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Menu mn)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_dataContext.MENU.Add(mn);
					_dataContext.SaveChanges();
					return RedirectToAction("Index");

				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View(mn);
		}

	}
}

Project/Areas/Admin/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Models;
using Project.Utilities;
using System.Data.Entity;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubjectController : Controller
    {
        private readonly DataContext _dataContext;
        public SubjectController(DataContext dataContext) {
            _dataContext = dataContext;
        }
        public IActionResult Index()
        {
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var listOfSubject = _dataContext.SUBJECT.OrderByDescending(x => x.SubjectId).ToList();
            
            return View("Index",listOfSubject);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var sb = _dataContext.SUBJECT.Where(x => x.SubjectId == id).ToList();
			Subject mn = sb.FirstOrDefault();
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);
            
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var dl = _dataContext.SUBJECT.Where(x => x.SubjectId == id).ToList();
			Subject deleSubject = dl.FirstOrDefault();
            if (deleSubject == null)
            {
                return NotFound();
            }
            _dataContext.SUBJECT.Remove(deleSubject);
            _dataContext.SaveChanges();
            return RedirectToAction("Index");
        }

		public IActionResult Edit(int id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var sb = _dataContext.SUBJECT.Where(x=>x.SubjectId == id).ToList();
			Subject mn = sb.FirstOrDefault();            
            if (mn == null)
			{
				return NotFound();
			}
			
			
			return View(mn);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Subject mn)
		{
			if (ModelState.IsValid)
			{
				if (ModelState.IsValid)
				{
					_dataContext.SUBJECT.Update(mn);
					_dataContext.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			return View(mn);
		}

		public IActionResult Create()
		{
			var mnList = (from m in _dataContext.SUBJECT
						  select new SelectListItem()
						  {
							  Text = m.SubjectName,
							  Value = m.SubjectId.ToString(),
						  }).ToList();			
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Subject mn)
		{
			try
			{
                if (ModelState.IsValid)
                {
                    _dataContext.SUBJECT.Add(mn);
                    _dataContext.SaveChanges();
                    return RedirectToAction("Index");

                }
            }
			catch (Exception ex)
			{
				throw ex;
			}						
			return View(mn);
		}
	}
}

Project/Areas/Admin/Views/Subject/Create.cshtml
@model Project.Models.Subject

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận thêm học phần</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm</h2>
        </div>
        <form method="post">
            <div bsp-validation-summary="All"></div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="SubjectName">Name</label>
                    <input type="text" class="form-control mb-3" asp-for="SubjectName" placeholder="Nhập tên Sản phẩm">
                    <span asp-validation-for="SubjectName" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Description">Description</label>
                    <input type="text" class="form-control mb-3" asp-for="Description" placeholder="Nhập mô tả">
                    <span asp-validation-for="Description" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                
                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Menu" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Subject/Delete.cshtml
@model Project.Models.Subject

@{
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
	<div class="pagetitle">
		<h2>Xác nhận xóa học phần</h2>
	</div>
	<div class="form-row">
		<div class="form-group col-md-6">
			<label asp-for="SubjectId">MenuId</label>
			<input type="text" class="form-control mb-3" asp-for="SubjectId" disabled>
		</div>
		<div class="form-group col-md-6">
			<label asp-for="SubjectName">MenuName</label>
			<input type="text" class="form-control mb-3" asp-for="SubjectName" disabled>
		</div>
	</div>

	<form asp-action="Delete" method="post">
		<input type="hidden" asp-for="SubjectId" />
		<a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
			<i class="bi bi-arrow-left-circle"></i>Quay lại
		</a>
		<button type="submit" class="btn btn-lg btn-danger p-2">
			<i class="bi bi-trash-fill"></i>Xóa học phần
		</button>

	</form>
</main>

Project/Areas/Admin/Views/Subject/Edit.cshtml
@model Project.Models.Subject
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận sửa học phần</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Sửa học phần</h2>
        </div>
        <form method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-row">
                <input type="text" class="form-control mb-3" asp-for="SubjectId" type="hidden">
                <div class="form-group col-md-6">
                    <label asp-for="SubjectName">Name</label>
                    <input type="text" class="form-control mb-3" asp-for="SubjectName" placeholder="Nhập tên học phần">
                    <span asp-validation-for="SubjectName" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-row">

                    <div class="form-group col-md-6">
                        <label asp-for="Description">Description</label>
                        <input type="text" class="form-control mb-3" asp-for="Description" placeholder="Thêm mô tả">
                        <span asp-validation-for="Description" class="alert-danger"></span>
                    </div>
                    

                    
                   
                    
                </div>
                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Menu" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Subject/Index.cshtml
@using Project.Models;
@model IList<Subject>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách học phần</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Subject" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1">Thêm học phần</i>
        </a>
    </p>

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Tiêu đề</th>
                                    <th class="col-2 text-center">Mô tả</th>
                                    
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.SubjectId</th>
                                        <td><a asp-controller="Menu" asp-action="Details" asp-route-id="@item.SubjectId" class="text-primary">@item.SubjectName</a></td>
                                        <td class="text-center">@item.Description</td>
                                       
                                        
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="Subject" asp-action="Edit" asp-route-id="@item.SubjectId" class="btn btn-primary btn-sm" title="Sửa thông tin học phần"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="Subject" asp-action="Delete" asp-route-id="@item.SubjectId" class="btn btn-danger btn-sm" title="Xóa thông tin học phần"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>