Project/Models/Exam.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    [Table("EXAMS", Schema = "ORACLE")]
    public class Exam

    {
        [Key]
        [Column("EXAMID")]
        public int ExamId { get; set; }

        [Column("EXAMNAME")]
        [Required(ErrorMessage = "Vui lòng nhập tên bài thi!")]
        public string? ExamName { get; set; }

        [Column("CREATEDBY")]
        public int? CreatedBy { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn môn học!")]
        [Column("SUBJECTID")]
        public int? SubjectId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập thời gian làm bài!")]
        [Column("TIME")]
        public int? Time { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng câu hỏi!")]
        [Column("NUMBEROFQUESTIONS")]
        public int? NumberOfQuestion { get; set; }

    }
}

Project/Models/ExamViewModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Models
{
    [Keyless]
    public class ExamViewModel
    {
        [Column("EXAMID")]
        public int ExamId { get; set; }

        [Column("EXAMNAME")]
        public string? ExamName { get; set; }

        [Column("CREATEBY")]
        public int? CreatedBy { get; set; }

        [Column("SUBJECTID")]
        public int? SubjectId { get; set; }
        [Column("TIME")]
        public int? Time { get; set; }
        [Column("SUBJECTNAME")]
        public string? SubjectName { get; set; }
        [Column("NUMBEROFQUESTIONS")]
        public int? NumberOfQuestion { get; set; }

    }
}

Project/Areas/Admin/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project.Models;
using System.Data.Entity;


namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExamController : Controller
    {
        private readonly DataContext _dataContext;
        public ExamController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public IActionResult Index()
        {
            var listOfExam = (from a in _dataContext.EXAMS
                              join b in _dataContext.SUBJECT
                              on a.SubjectId equals b.SubjectId
                              orderby a.ExamId
                              select new ExamViewModel()
                              {
                                  ExamId = a.ExamId,
                                  ExamName = a.ExamName,
                                  CreatedBy = a.CreatedBy,
                                  Time = a.Time,
                                  SubjectId = a.SubjectId,
                                  NumberOfQuestion = a.NumberOfQuestion,
                                  SubjectName = b.SubjectName
                              }).ToList();

            return View("Index", listOfExam);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var sb = _dataContext.EXAMS.Where(x => x.ExamId == id).ToList();
            Exam mn = sb.FirstOrDefault();
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var dl = _dataContext.EXAMS.Where(x => x.SubjectId == id).ToList();
            Exam deleSubject = dl.FirstOrDefault();
            if (deleSubject == null)
            {
                return NotFound();
            }
            _dataContext.EXAMS.Remove(deleSubject);
            _dataContext.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var subjectList = (from
                            b in _dataContext.SUBJECT
                               select new SelectListItem()
                               {
                                   Text = b.SubjectName,
                                   Value = b.SubjectId.ToString(),
                               }).ToList();
            subjectList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.subjectList = subjectList;

            var sb = _dataContext.EXAMS.Where(x => x.ExamId == id).ToList();
            Exam mn = sb.FirstOrDefault();
            if (mn == null)
            {
                return NotFound();
            }


            return View(mn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Exam ex)
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _dataContext.EXAMS.Update(ex);
                    _dataContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(ex);
        }

        public IActionResult Create()
        {
            var subjectList = (from
                             b in _dataContext.SUBJECT
                               select new SelectListItem()
                               {
                                   Text = b.SubjectName,
                                   Value = b.SubjectId.ToString(),
                               }).ToList();
            subjectList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.subjectList = subjectList;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Exam mn)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _dataContext.EXAMS.Add(mn);
                    _dataContext.SaveChanges();
                    return RedirectToAction("Index",mn);

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(mn);
        }

        public IActionResult Setting(int id)
        {
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var sb = _dataContext.EXAMS.Where(x => x.ExamId == id).ToList();
			Exam mn = sb.FirstOrDefault();
			if (mn == null)
			{
				return NotFound();
			}
			return View(mn);

			
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Setting(int id, int chapter1,int chapter2, int chapter3, int chapter4, int chapter5, int chapter6, int chapter7, int chapter8)
        {
			var ex = _dataContext.EXAMS.Where(x => x.SubjectId == id).ToList();
			Exam mn = ex.FirstOrDefault();
			if ((chapter1 + chapter2 + chapter3 + chapter4 + chapter5 + chapter6 + chapter7 + chapter8)!= mn.NumberOfQuestion)
                return NotFound();
            else
            {
                //var c1 = _dataContext.QUESTIONS.Where(a => a.SubjectId == id);
            }    
            return View("Index");
        }
    }
}

Project/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;
using Project.Models;
using Project.Utilities;
using System.Collections;
using System.Data.Entity;
using System.Net.WebSockets;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
	
    public class MenuController : Controller
    {
		private readonly DataContext _dataContext;
		public String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
		
        
        public MenuController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public IActionResult Index()
        {
            if (!Functions.IsLogin())
                return RedirectToAction("Index", "Login");
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
			
            return View(listofMenu);
			
        }
	
		public IActionResult Delete(int? id)
		{
			var query = "delete from menu where menuid =" + id;
			 String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
			var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
			connection.Open();
			var sourQuery = connection.CreateCommand();
			sourQuery.CommandText = query;
			sourQuery.ExecuteNonQuery();
			//var reader = sourQuery.ExecuteReader();
			connection.Close();
            var sql = "SELECT * FROM menu ORDER BY menu.MenuId";
            var listofMenu = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return View("Index",listofMenu);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
            var sql = "SELECT * FROM menu ";
            var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
            return RedirectToAction("Index",mn);
		}

		public IActionResult Edit(int? id)
		{
			if (id == null)
				return NotFound();
			var sql = "SELECT * FROM menu where menu.MenuId ="+id;
			var mn = _dataContext.MENU.FromSqlRaw(sql).ToList();
			return View(mn);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Menu mn)
		{
			if(ModelState.IsValid)
			{
				var query = "update menu mn set mn.MenuName = '"+mn.MenuName+ "' where mn.MenuId = "+mn.MenuId;
				String conString = @"Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=ORACLE;Password=161199;";
				var connection = new Oracle.ManagedDataAccess.Client.OracleConnection(conString);
				connection.Open();
				var sourQuery = connection.CreateCommand();
				sourQuery.CommandText = query;
				sourQuery.ExecuteNonQuery();
				//var reader = sourQuery.ExecuteReader();
				connection.Close();
			}
			return View(mn);
		}

		public IActionResult Create()
		{
            var parentList = (from
                             b in _dataContext.MENU
                               select new SelectListItem()
                               {
                                   Text = b.MenuName,
                                   Value = b.MenuId.ToString(),
                               }).ToList();
            parentList.Insert(0, new SelectListItem()
            {
                Text = "---Select---",
                Value = "0"
            });
            ViewBag.parentList = parentList;

            var menuOrderList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Vị trí 1", Value = "1" },
                new SelectListItem { Text = "Vị trí 2", Value = "2" },
                new SelectListItem { Text = "Vị trí 3", Value = "3" },
                new SelectListItem { Text = "Vị trí 4", Value = "4" },
                new SelectListItem { Text = "Vị trí 5", Value = "5" },
                new SelectListItem { Text = "Vị trí 6", Value = "6" },
                new SelectListItem { Text = "Vị trí 7", Value = "7" },
                new SelectListItem { Text = "Vị trí 8", Value = "8" },
            };
            ViewBag.MenuOrderList = menuOrderList;
            return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Menu mn)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_dataContext.MENU.Add(mn);
					_dataContext.SaveChanges();
					return RedirectToAction("Index");

				}
			}
			catch (Exception ex)
			{
				throw ex;
			}
			return View(mn);
		}

	}
}

Project/Controllers/ExamController.cs
using Project.Models;
using Project.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project.Utilities;

namespace Project.Controllers
{
    public class ExamController : Controller
    {
        private readonly DataContext _context;
        public ExamController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var mnList = (from m in _context.SUBJECT
                          select new SelectListItem()
                          {
                              Text = m.SubjectName,
                              Value = m.SubjectId.ToString(),
                          }).ToList();
            ViewBag.mnList = mnList;

            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Exam exams)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exams);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult CreateDetail(List<QuesOfExam> model,int ExamId)
        {
            if (ModelState.IsValid)
            {
                int totalQuestions = model.Count;
                int correctAnswers = 0;

                // Xử lý danh sách câu trả lời
                foreach (var question in model)
                {
                    int examIdIneed = question.ExamId;
                    if (question.UserAnswer == question.CorrectOption)
                    {
                        correctAnswers++;
                    }
                }

                // Tính tỷ lệ đúng
                double accuracy = (double)correctAnswers / totalQuestions ;
                if(Functions.IsLogin())
                {
                    
                    Result result = new Result();
                    result.UserId = Functions._UserID;
                    result.ExamId = ExamId;
                    result.Session = "Test";
                    result.Score = accuracy;
                    _context.RESULTS.Add(result);
                    _context.SaveChanges();
                }    


                // Truyền dữ liệu qua ViewBag
                
                ViewBag.TotalQuestions = totalQuestions;
                ViewBag.CorrectAnswers = correctAnswers;
                ViewBag.Accuracy = accuracy;

                return View("Result"); // Hiển thị View Result
            }
            else
            {
                return View("Index");
            }
        }

    }
}

Project/Areas/Admin/Views/Exam/Create.cshtml
@model Project.Models.Exam

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận thêm đề thi</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Thêm</h2>
        </div>
        <form method="post" asp-validation-summary="All">
            <div bsp-validation-summary="All"></div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="ExamName">Tên bài thi</label>
                    <input type="text" class="form-control mb-3" asp-for="ExamName" placeholder="Nhập tên bài thi" required>
                    <span asp-validation-for="ExamName" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="SubjectId">Chọn Môn học</label>
                <select asp-for="SubjectId" class="form-control" asp-items="@(new SelectList(ViewBag.subjectList,"Value","Text"))"></select>
                <span asp-validation-for="SubjectId" class="alert-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Time">Thời gian làm bài</label>
                    <input type="number" class="form-control mb-3" asp-for="Time" min="5" max="120" placeholder="Nhập thời gian" required>
                    <span asp-validation-for="Time" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="NumberOfQuestion">Số lượng câu hỏi</label>
                    <input type="number" class="form-control mb-3" asp-for="NumberOfQuestion" min="5" max="100" placeholder="Nhập số lượng câu hỏi" required>
                    <span asp-validation-for="NumberOfQuestion" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">

                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Menu" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Exam/Delete.cshtml
@model Project.Models.Exam

@{
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
	<div class="pagetitle">
		<h2>Xác nhận xóa bài thi</h2>
	</div>
	<div class="form-row">
		<div class="form-group col-md-6">
			<label asp-for="ExamId">Mã bài thi</label>
			<input type="text" class="form-control mb-3" asp-for="ExamId" disabled>
		</div>
		<div class="form-group col-md-6">
			<label asp-for="ExamName">Tên bài thi</label>
			<input type="text" class="form-control mb-3" asp-for="ExamName" disabled>
		</div>
	</div>

	<form asp-action="Delete" method="post">
		<input type="hidden" asp-for="ExamId" />
		<a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
			<i class="bi bi-arrow-left-circle"></i>Quay lại
		</a>
		<button type="submit" class="btn btn-lg btn-danger p-2">
			<i class="bi bi-trash-fill"></i>Xóa bài thi
		</button>

	</form>
</main>

Project/Areas/Admin/Views/Exam/Edit.cshtml
@model Project.Models.Exam
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xác nhận sửa thông tin bài thi</h2>
    </div>
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Sửa câu hỏi</h2>
        </div>
        <form method="post">
            <div asp-validation-summary="All"></div>
            <div class="form-row">
                <input type="text" class="form-control mb-3" asp-for="ExamId" type="hidden">
                <div class="form-group col-md-6">
                    <label asp-for="ExamName">Tên bài thi</label>
                    <input type="text" class="form-control mb-3" asp-for="ExamName" placeholder="Nhập tên bài thi" required>
                    <span asp-validation-for="ExamName" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-row">

                    <div class="form-group col-md-6">
                        <label asp-for="Time">Thời gian</label>
                        <input type="number" class="form-control mb-3" asp-for="Time" placeholder="Nhập thời gian" required min="5" max="100">
                        <span asp-validation-for="Time" class=" alert-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="NumberOfQuestion">Số câu hỏi</label>
                        <input type="number" class="form-control mb-3" asp-for="NumberOfQuestion" placeholder="Nhập số lượng câu hỏi" required min="5" max="100">
                        <span asp-validation-for="NumberOfQuestion" class=" alert-danger"></span>
                    </div>
                   
                    <div class="form-group col-md-6">
                        <label asp-for="SubjectId">Chọn học phần</label>
                        <select asp-for="SubjectId" class="form-control" asp-items="@(new SelectList(ViewBag.subjectList,"Value","Text"))"></select>
                        <span asp-validation-for="SubjectId" class="alert-danger"></span>
                    </div>



                </div>
                <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-pluss-fill"></i>Lưu</button>
                <a asp-controller="Exam" asp-action="Index" class="btn btn-lg btn-warning p-2">Quay lại</a>
            </div>
        </form>
    </div>
</main>

Project/Areas/Admin/Views/Exam/Index.cshtml
@using Project.Models;
@model IList<ExamViewModel>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách bài thi</h2>
    </div>

    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Exam" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1">Thêm bài thi
        </a>
    </p>

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Tên bài thi</th>
                                    <th class="col-2 text-center">Người tạo</th>
                                    <th class="col-2 text-center">Môn học</th>
                                    <th class="col-1 text-center">Thời gian</th>
                                    <th class="col-1 text-center">Số câu hỏi</th>
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.ExamId</th>
                                        <td><a asp-controller="Menu" asp-action="Details" asp-route-id="@item.SubjectId" class="text-primary">@item.ExamName</a></td>
                                        <td class="text-center">@item.CreatedBy</td>
                                        <td class="text-center">@item.SubjectName</td>
                                        <td class="text-center">@item.Time</td>
                                        <td class="text-center">@item.NumberOfQuestion</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="Exam" asp-action="Edit" asp-route-id="@item.SubjectId" class="btn btn-primary btn-sm" title="Sửa thông tin học phần"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="Exam" asp-action="Delete" asp-route-id="@item.SubjectId" class="btn btn-danger btn-sm" title="Xóa thông tin học phần"><i class="bi bi-trash"></i></a>
                                            <a asp-area="Admin" asp-controller="Exam" asp-action="Setting" asp-route-id="@item.SubjectId" class="btn btn-secondary btn-sm" title="Cài đặt"><i class="bi bi-gear"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Project/Areas/Admin/Views/Exam/Setting.cshtml
@model Project.Models.Exam

@{
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<main id="main" class="main">
	<div class="pagetitle">
		<h2>Cấu hình bài thi</h2>
	</div>
	<div class="form-row">
		<div class="form-group col-md-6">
			<label asp-for="ExamId">Mã bài thi</label>
			<input type="text" class="form-control mb-3" asp-for="ExamId" disabled>
		</div>
		<div class="form-group col-md-6">
			<label asp-for="ExamName">Tên bài thi</label>
			<input type="text" class="form-control mb-3" asp-for="ExamName" disabled>
		</div>
		<div class="form-group col-md-6">
			<label asp-for="NumberOfQuestion">Số lượng câu hỏi</label>
			<input type="text" class="form-control mb-3" asp-for="NumberOfQuestion" disabled>
		</div>
		<div class="form-group col-md-6">
			<label asp-for="Time">Thời gian làm bài</label>
			<input type="text" class="form-control mb-3" asp-for="Time" disabled>
		</div>
	</div>

	<form asp-action="Setting" method="post">
		<input type="hidden" asp-for="ExamId" />
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter1">Nhập số lượng câu hỏi chương I</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter2">Nhập số lượng câu hỏi chương II</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter3">Nhập số lượng câu hỏi chương III</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter4">Nhập số lượng câu hỏi chương IV</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter6">Nhập số lượng câu hỏi chương VI</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter7">Nhập số lượng câu hỏi chương VII</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="chapter8">Nhập số lượng câu hỏi chương VIII</label>
				<input type="number" required min="0" max="50" class="form-control mb-3" name="ChapterI" placeholder="Nhập số lượng câu hỏi chương I">
			</div>
		</div>
		<a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
			<i class="bi bi-arrow-left-circle"></i>Quay lại
		</a>
		<button type="submit" class="btn btn-lg btn-danger p-2">
			<i class="bi bi-trash-fill"></i>Cập nhật
		</button>

	</form>
</main>